(() => {
  const keys = ['mode','myHandle','dailyCap','batchSize','minDelaySec','maxDelaySec','preSendMinSec','preSendMaxSec','authorCooldownHours','endpoint','apiPath','apiKey','model','prompt','prompts','normalizeDashes','lowercaseReplies','minorTypoChance'];
  const $ = (id) => document.getElementById(id);
  function show(message) { $('status').textContent = message; }
  function renderLogs(logs) { const items = Array.isArray(logs) ? logs : []; const esc = (value) => String(value).replace(/[&<>"']/g, (ch) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[ch])); $('logs').innerHTML = items.map((x) => { const message = String(x.message || ''); const kind = /AI RESULT ERROR|AI ERROR|EXCEPTION|ERROR/i.test(message) ? 'log-error' : /RETRY|RATE LIMIT/i.test(message) ? 'log-retry' : /SEND click|DRAFT READY/i.test(message) ? 'log-send' : /AI OK/i.test(message) ? 'log-ok' : /SCROLL|FEED/i.test(message) ? 'log-scroll' : /RUN /i.test(message) ? 'log-run' : 'log-muted'; return `<span class="log-line ${kind}"><span class="log-time">[${esc(new Date(x.ts).toLocaleTimeString())}]</span> ${esc(message)}</span>`; }).join('') || '<span class="log-line log-muted">Логов пока нет.</span>'; $('logs').scrollTop = $('logs').scrollHeight; }
  function renderChart(history) { const items = (Array.isArray(history) ? history : []).filter((item) => Number.isFinite(Number(item.ts))); const chart = $('dash-chart'); if (!items.length) { chart.innerHTML = '<div class="chart-empty">История ответов пока пуста.</div>'; return; } const days = new Map(); items.forEach((item) => { const date = new Date(Number(item.ts)); const key = `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`; const current = days.get(key) || { count: 0, first: Number(item.ts), last: Number(item.ts) }; current.count++; current.first = Math.min(current.first, Number(item.ts)); current.last = Math.max(current.last, Number(item.ts)); days.set(key, current); }); const points = [...days.entries()].sort((a, b) => a[0].localeCompare(b[0])); const max = Math.max(...points.map(([, value]) => value.count), 1); const width = Math.max(520, points.length * 42); const height = 230; const pad = { top: 16, right: 12, bottom: 34, left: 30 }; const plotW = width - pad.left - pad.right; const plotH = height - pad.top - pad.bottom; const barW = Math.max(4, Math.min(28, plotW / points.length * .62)); const esc = (value) => String(value).replace(/[&<>"']/g, (ch) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[ch])); const grid = [0, .5, 1].map((ratio) => { const y = pad.top + plotH - ratio * plotH; return `<line class="chart-grid" x1="${pad.left}" y1="${y}" x2="${width - pad.right}" y2="${y}"/><text class="chart-label" x="2" y="${y + 4}">${Math.round(max * ratio)}</text>`; }).join(''); const bars = points.map(([key, value], index) => { const x = pad.left + (index + .5) * (plotW / points.length) - barW / 2; const barH = value.count / max * plotH; const y = pad.top + plotH - barH; const label = key.slice(5); const tooltip = `${key} · ${value.count} repl${value.count === 1 ? 'y' : 'ies'} · ${new Date(value.first).toLocaleTimeString()}–${new Date(value.last).toLocaleTimeString()}`; return `<g><title>${esc(tooltip)}</title><rect class="chart-bar" x="${x.toFixed(1)}" y="${y.toFixed(1)}" width="${barW.toFixed(1)}" height="${barH.toFixed(1)}"/><text class="chart-label" text-anchor="middle" x="${(x + barW / 2).toFixed(1)}" y="${height - 12}">${esc(label)}</text><text class="chart-label" text-anchor="middle" x="${(x + barW / 2).toFixed(1)}" y="${Math.max(12, y - 4)}">${value.count}</text></g>`; }).join(''); chart.innerHTML = `<svg viewBox="0 0 ${width} ${height}" role="img" aria-label="Количество ответов по дням">${grid}${bars}</svg>`; }
  function renderDashboard() { chrome.storage.local.get({ config: XAR.DEFAULTS, runtimeState: {}, debugLogs: [], replyHistory: [], emergencyStop: false }, (s) => { const c = { ...XAR.DEFAULTS, ...(s.config || {}) }; const state = s.runtimeState || {}; const logs = Array.isArray(s.debugLogs) ? s.debugLogs : []; const sent = Number(state.sentToday) || 0; const cap = Math.max(1, Number(c.dailyCap) || XAR.DEFAULTS.dailyCap); const cooldownMs = Math.max(0, Number(c.authorCooldownHours) || 0) * 60 * 60 * 1000; const authors = Object.values(state.authorLastSent || {}).filter((ts) => cooldownMs > 0 && Date.now() - Number(ts) < cooldownMs).length; const errors = logs.filter((x) => /error|ошиб|exception/i.test(String(x.message || ''))).length; const aiRequests = logs.filter((x) => /AI REQUEST/i.test(String(x.message || ''))).length; const aiErrors = logs.filter((x) => /AI RESULT ERROR|AI ERROR/i.test(String(x.message || ''))).length; const runs = logs.filter((x) => /RUN finished/i.test(String(x.message || ''))).length; const skipped = logs.filter((x) => /AI SKIP|USER DISCARDED|RETRY exhausted/i.test(String(x.message || ''))).length; $('dash-sent').textContent = sent; $('dash-cap').textContent = cap; $('dash-total').textContent = Array.isArray(s.replyHistory) ? s.replyHistory.length : 0; $('dash-cooldown').textContent = authors; const dashErrors = $('dash-errors'); if (dashErrors) dashErrors.textContent = errors; $('dash-ai-requests').textContent = aiRequests; $('dash-ai-errors').textContent = aiErrors; $('dash-runs').textContent = runs; $('dash-skipped').textContent = skipped; $('dash-progress').style.width = `${Math.min(100, sent / cap * 100)}%`; $('dash-progress-label').textContent = `${sent} / ${cap} ответов`; $('dash-mode').textContent = s.emergencyStop ? 'STOPPED' : String(c.mode || 'draft').toUpperCase(); $('dash-batch').textContent = `Batch: ${c.batchSize || XAR.DEFAULTS.batchSize}`; $('dash-events').textContent = `Событий в журнале: ${logs.length}`; const last = logs[logs.length - 1]; $('dash-last').textContent = `Последнее событие: ${last ? `[${new Date(last.ts).toLocaleTimeString()}] ${last.message}` : 'нет'}`; $('dash-cooldown-detail').textContent = `Cooldown: ${c.authorCooldownHours || XAR.DEFAULTS.authorCooldownHours} ч · авторов: ${authors}`; const recent = logs.slice(-8).reverse(); $('dash-recent').innerHTML = recent.length ? recent.map((x) => `<li>[${new Date(x.ts).toLocaleTimeString()}] ${String(x.message).replace(/[&<>"']/g, (ch) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[ch]))}</li>`).join('') : '<li>Событий пока нет.</li>'; renderChart(s.replyHistory); }); }
  function loadLogs() { chrome.storage.local.get({ debugLogs: [], runtimeStatus: '' }, (s) => { renderLogs(s.debugLogs); if (s.runtimeStatus) show(s.runtimeStatus); }); }
  function load() { chrome.storage.local.get({ config: XAR.DEFAULTS, emergencyStop: false }, (s) => { const c = { ...XAR.DEFAULTS, ...(s.config || {}) }; keys.forEach((k) => { if ($(k).type === 'checkbox') $(k).checked = Boolean(c[k]); else $(k).value = c[k] ?? ''; }); if (s.emergencyStop) show('Автоответы остановлены аварийным переключателем.'); renderDashboard(); }); }
  $('openrouter').addEventListener('click', () => { $('endpoint').value = 'https://openrouter.ai/api/v1'; $('apiPath').value = '/chat/completions'; $('model').value = 'openrouter/free'; show('OpenRouter Free выбран. Вставьте API key и сохраните.'); });
  $('resetPrompt').addEventListener('click', () => { $('prompt').value = XAR.DEFAULTS.prompt; show('Новый короткий prompt выбран. Нажмите «Сохранить настройки».'); });
  $('save').addEventListener('click', () => { const config = {}; keys.forEach((k) => { config[k] = $(k).type === 'checkbox' ? $(k).checked : $(k).value; }); ['dailyCap','batchSize','minDelaySec','maxDelaySec','preSendMinSec','preSendMaxSec','authorCooldownHours'].forEach((k) => { config[k] = Number(config[k]) || XAR.DEFAULTS[k]; }); config.minorTypoChance = Math.min(10, Math.max(0, Number.isFinite(Number(config.minorTypoChance)) ? Number(config.minorTypoChance) : XAR.DEFAULTS.minorTypoChance)); if (config.maxDelaySec < config.minDelaySec) config.maxDelaySec = config.minDelaySec; if (config.preSendMaxSec < config.preSendMinSec) config.preSendMaxSec = config.preSendMinSec; chrome.storage.local.set({ config, emergencyStop: false }, () => show('Сохранено.')); });
  $('start').addEventListener('click', () => {
    chrome.storage.local.set({ emergencyStop: false }, () => chrome.tabs.query({ active: true, currentWindow: true }, (tabs) => {
      const tab = tabs && tabs[0];
      if (!tab?.id || !/^https:\/\/(x\.com|twitter\.com)\//i.test(tab.url || '')) { show('Откройте вкладку x.com или twitter.com.'); return; }
      chrome.tabs.sendMessage(tab.id, { type: 'START_RUN' }, (r) => show(chrome.runtime.lastError ? 'Обновите вкладку X после установки расширения.' : (r?.ok ? 'Запуск начат.' : `Не удалось запустить: ${r?.reason || 'ошибка'}`)));
    }));
  });
  $('stop').addEventListener('click', () => chrome.runtime.sendMessage({ type: 'EMERGENCY_STOP' }, (r) => show(r?.ok ? 'Автоответы остановлены.' : 'Не удалось остановить.')));
  $('clearLogs').addEventListener('click', () => chrome.storage.local.set({ debugLogs: [] }, () => { renderLogs([]); show('Логи очищены.'); }));
  $('dash-settings').addEventListener('click', () => { document.querySelector('[data-tab="settings"]').click(); });
  $('dash-clear-logs').addEventListener('click', () => chrome.storage.local.set({ debugLogs: [] }, () => { renderLogs([]); renderDashboard(); show('Логи очищены.'); }));
  document.querySelectorAll('[data-tab]').forEach((tab) => tab.addEventListener('click', () => { document.querySelectorAll('[data-tab]').forEach((item) => item.classList.toggle('active', item === tab)); document.querySelectorAll('.tab-panel').forEach((panel) => { panel.hidden = panel.id !== `tab-${tab.dataset.tab}`; }); if (tab.dataset.tab === 'dashboard') renderDashboard(); }));
  chrome.storage.onChanged.addListener((changes, area) => { if (area === 'local' && changes.debugLogs) { renderLogs(changes.debugLogs.newValue); renderDashboard(); } if (area === 'local' && (changes.runtimeState || changes.config || changes.emergencyStop || changes.replyHistory)) renderDashboard(); });
  chrome.storage.onChanged.addListener((changes, area) => { if (area === 'local' && changes.runtimeStatus) show(changes.runtimeStatus.newValue || ''); });
  load(); loadLogs();
})();
